# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fav_quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Not Available', max_length=45)),
                ('last_name', models.CharField(default='Not Available', max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.TextField(default='Not Available')),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='quotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.User'),
        ),
        migrations.AddField(
            model_name='fav_quotes',
            name='quotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Quotes'),
        ),
        migrations.AddField(
            model_name='fav_quotes',
            name='user',
            field=models.ManyToManyField(to='quotes.User'),
        ),
    ]
