# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='quotedby',
            field=models.CharField(default='Not Available', max_length=45),
        ),
    ]
