# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20170127_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav_quotes',
            name='quotes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.Quotes'),
        ),
    ]
