# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20170127_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav_quotes',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='fav_quotes',
            name='user',
        ),
    ]
