# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_delete_fav_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='fav_quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.ManyToManyField(to='quotes.Quotes')),
                ('user', models.ManyToManyField(to='quotes.User')),
            ],
        ),
    ]
