# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20170127_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav_quotes',
            name='quotes',
        ),
        migrations.AddField(
            model_name='fav_quotes',
            name='quotes',
            field=models.ManyToManyField(to='quotes.Quotes'),
        ),
    ]
