# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_auto_20170127_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav_quotes',
            name='quotes',
        ),
        migrations.AddField(
            model_name='fav_quotes',
            name='quotes',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='quotes.Quotes'),
        ),
    ]
