# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_auto_20170127_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav_quotes',
            name='user',
        ),
        migrations.AddField(
            model_name='fav_quotes',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='quotes.User'),
        ),
    ]
